name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * 4"

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu", "macos", "windows"]
    runs-on: ${{ matrix.os }}-latest

    steps:
      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v6

      - name: Clone and build V (Unix)
        if: runner.os != 'Windows'
        run: |
          git clone --depth 1 https://github.com/vlang/v "${{ runner.temp }}/vlang"
          cd "${{ runner.temp }}/vlang"
          make
          echo "${{ runner.temp }}/vlang" >> "$GITHUB_PATH"

      - name: Clone and build V (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          git clone --depth 1 https://github.com/vlang/v "${{ runner.temp }}\vlang"
          cd "${{ runner.temp }}\vlang"
          .\makev.bat -msvc
          echo ${{ runner.temp }}\vlang>>%GITHUB_PATH%

      - name: Check if code is formatted
        run: |
          v fmt -diff .
          v fmt -verify .

      - name: Run tests
        run: v test .

      - name: Build ${{ github.event.repository.name }}
        run: v .
