name: Upload artifacts

on:
  push:
    tags:
      - "v*" # matches v1.0.1, v1.2, v2, etc

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu", "macos", "windows"]
    runs-on: ${{ matrix.os }}-latest

    steps:
      - name: Setup Vlang
        uses: vlang/setup-v@v1.4
        with:
          check-latest: true

      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v6

      - name: Check if code is formatted
        run: |
          v fmt -diff .
          v fmt -verify .

      - name: Build ${{ github.event.repository.name }}
        run: |
          v build.vsh

      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: klonol-${{ matrix.os }}
          path: bin
          retention-days: 15

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v8

      - name: Zip artifacts
        run: |
          for os in ubuntu macos windows; do
            (cd klonol-$os && zip -r ../klonol-$os.zip .)
          done

      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true
          files: klonol-*.zip
